services:
    EcPhp\EcReverseProxyBundle\EventListener\SetEcReverseProxyHeaders:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 4096 }
